"""
structure_data.py — OCR Text → Structured JSON
================================================
Sends raw OCR text from a survey PDF to Gemini and extracts structured fields.

EXTRACTION RULES:
─────────────────────────────────────────────────────────────────────────────
  FILLED BY LLM (from the paper):
    - type_of_issue     : Short category label (Medical / Food / Water / etc.)
    - what_is_the_issue : LLM synthesizes a clear 1-2 sentence description
    - area              : ONLY if explicitly mentioned in the paper, else null
    - city              : ONLY if explicitly mentioned in the paper, else null
    - pincode           : ONLY if explicitly mentioned in the paper, else null
    - date              : ONLY if mentioned, else null

  FILLED BY LLM ONLY IF MENTIONED IN THE PDF:
    - num_ppl_affected  : Integer — ONLY if the count is stated in the paper
    - num_vol_needed    : Integer — ONLY if the count is stated in the paper

  NOT TOUCHED HERE (filled by system / model.py):
    - surid             : Auto-generated by server
    - reported_by       : Auto-filled from logged-in field worker
    - created_at        : Timestamped by server
    - status            : Defaults to "pending"
    - source            : Auto-tagged (pdf / app / web)
    - urgency           : Estimated by model.py (LLM)
    - coordinates       : Geocoded by model.py
    - req_skillset      : Recommended by model.py (LLM)
    - estimated_days    : Computed by model.py (formula)
    - max_points        : Computed by model.py (formula)
─────────────────────────────────────────────────────────────────────────────
"""

import os
import json
import logging
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

EXTRACTION_PROMPT = """
You are a data extraction specialist for an NGO disaster-relief platform.
Below is raw text extracted via OCR from hand-filled community survey forms.

YOUR TASK:
Identify each individual survey report in the text and extract the fields below.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FIELDS TO EXTRACT (for each survey):

1. type_of_issue
   Short category label. Pick exactly ONE from:
   Food | Water | Medical | Logistics | Sanitation/Infrastructure | Education | Other

2. what_is_the_issue
   Write a clear, concise 1–2 sentence description of the problem.
   Synthesize and clean up OCR noise — DO NOT copy raw text verbatim.

3. date
   Date of the report in YYYY-MM-DD format.
   → Set to null if not mentioned.

4. area
   Locality / neighbourhood name if explicitly stated in the paper.
   → Set to null if NOT clearly written.

5. city
   City name if explicitly stated in the paper.
   → Set to null if NOT clearly written.

6. pincode
   Postal/PIN code if explicitly written in the paper.
   → Set to null if NOT clearly written.

7. num_ppl_affected
   Integer count of people affected.
   → Set to null ONLY if the number is NOT stated in the paper.
   → Do NOT guess or estimate this value — extract it or return null.

8. num_vol_needed
   Integer count of volunteers needed.
   → Set to null ONLY if the number is NOT stated in the paper.
   → Do NOT guess or estimate this value — extract it or return null.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRICT RULES:
- DO NOT fabricate any values. If a field is absent from the paper, use null.
- DO NOT add fields not listed above.
- Output a VALID JSON array of objects — one object per survey found.
- Strip any markdown fences from your response.

EXAMPLE OUTPUT:
[
  {{
    "type_of_issue": "Medical",
    "what_is_the_issue": "Elderly residents in the area are experiencing respiratory issues following flooding.",
    "date": "2026-04-15",
    "area": "Velachery",
    "city": "Chennai",
    "pincode": "600042",
    "num_ppl_affected": 80,
    "num_vol_needed": null
  }}
]

RAW TEXT:
{raw_text}
"""


def structure_text_with_gemini(input_file: str, output_file: str) -> list:
    """
    Reads raw OCR text from `input_file`, sends it to Gemini,
    and writes structured JSON to `output_file`.
    Returns the list of extracted survey dicts.
    """
    with open(input_file, "r", encoding="utf-8") as f:
        raw_text = f.read()

    model = genai.GenerativeModel("gemini-2.5-flash")
    prompt = EXTRACTION_PROMPT.format(raw_text=raw_text)

    logger.info("Sending OCR text to Gemini for structured extraction...")
    response = model.generate_content(prompt)

    raw_json = response.text.replace("```json", "").replace("```", "").strip()

    try:
        data = json.loads(raw_json)
        if isinstance(data, dict):
            data = [data]

        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        logger.info(f"Extracted {len(data)} survey report(s) → {output_file}")
        return data

    except json.JSONDecodeError as e:
        logger.error(f"JSON parse error: {e}")
        logger.error(f"Raw Gemini response: {response.text[:500]}")
        raise RuntimeError("Gemini returned invalid JSON. Check the raw OCR text quality.")


if __name__ == "__main__":
    structure_text_with_gemini(
        "./data/output/raw_extracted_content.txt",
        "./data/structured_output/structured_surveys.json",
    )